Some fixes
avto-dev/b2b-api-php-laravel pull request #5
Opened 2018-11-13 12:47 UTC by eldario

| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No

## Description

> Changed the return type of webhook. 

Fixes # (issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I wrote unit tests for my code
- [ ] I have made changes in [CHANGELOG.md](https://github.com/avto-dev/b2b-api-php-laravel/blob/master/CHANGELOG.md) file

2018-11-13 19:00 UTC, tarampampam commented
Updated changeslog required

2018-11-13 19:01 UTC, tarampampam commented
Also - make an issue first (and link issue with entry into changeslog file)

2018-11-14 06:30 UTC, tarampampam requested changes

2018-11-14 06:30 UTC, tarampampam commented on CHANGELOG.md
> +## [v2.4.0] - 2018-11-13
Где сноска ссылки `[v2.4.0]`?

2018-11-14 06:32 UTC, tarampampam commented
Update PR description (link to the issue) and check checkboxes statuses

2018-11-14 07:32 UTC, eldario commented on CHANGELOG.md
> +## [v2.4.0] - 2018-11-13
Исправил

2018-11-14 09:52 UTC, tarampampam approved these changes

2018-11-14 09:52 UTC, merged

2018-11-14 09:52 UTC, tarampampam commented
All looks file! Thx for your PR!